port: 1235

keep_files:
  - assets/css/tailwind.css
  - generated

include:
  - _pages

exclude:
  - package.json
  - package-lock.json
  - readme.md

incremental: true

plugins:
  - jekyll-seo-tag
  - jekyll_picture_tag
  - jekyll-sitemap

defaults:
  - scope:
      path: "_posts"
    values:
      type: "post"

  - scope:
      path: "portfolio/_posts"
    values:
      type: "portfolio"

picture:
  suppress_warnings: true
  #ignore_missing_images: true

# SEO stuff
title: Keen Development
tagline: Professional and reliable full-stack development
description: Experienced full-stack web developer specialising in Elm, Elixir, Phoenix, Typescript, React, Tailwind, HTML, CSS, PHP, Symfony, Sonata and more.
home_text: I am a freelance full-stack web developer and consultant specialising in Elm, Elixir, Phoenix, Typescript, React, HTML, CSS, PHP, Symfony, Sonata and more. I am knowledgeable and experienced in a wide variety of technologies, languages, frameworks and platforms. I am highly skilled in software engineering and systems architecture and my work is always robust, reliable, maintainable and elegantly coded. I have over 20 years hands-on experience in the industry and hold a degree in Computer Science from the University of Edinburgh.

# Blog
archive_from: 2019-01-01 00:00:00

baseurl: /keendevelopment