port: 1235

keep:
  - assets/css/tailwind.css

include:
  - _pages

exclude:
  - package.json
  - package-lock.json
  - readme.md

incremental: true

plugins:
  - jekyll-responsive-image
  - jekyll-seo-tag

responsive_image:
  template: _includes/responsive-picture.html
  sizes:
    - width: 320
    - width: 480
    - width: 800

defaults:
  - scope:
      path: "_posts"
    values:
      type: "post"

  - scope:
      path: "portfolio/_posts"
    values:
      type: "portfolio"

# SEO stuff
title: Keen Development
tagline: Professional and reliable full-stack development
description: Experienced full-stack web developer specialising in Elm, Rescript, Elixir, Typescript, Javascript, PHP and more.
