name: Publish Jekyll site

on: push

jobs:
  jekyll:
    runs-on: ubuntu-20.04
    env:
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v2

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Build tailwind.css in-place
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install
      - run: yarn postcss assets/css/tailwind.css -o assets/css/tailwind.css

      # Build the site in the target branch
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: "gh-pages"
          pre_build_commands: |
            apk --update add vips vips-tools 
